version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Type Check
          command: yarn type-check
      - run:
          name: Verify Code Style
          command: yarn prettier:check
      - run:
          name: Verify Code Quality and Integrity
          command: yarn eslint:check
      - run:
          name: Verify Stylesheets Quality and Integrity
          command: yarn stylelint:check
      - run:
          name: Test Next build
          command: yarn build
      - run:
          name: Test Storybook build
          command: yarn build-storybook
      - run:
          name: Run tests
          command: yarn test
